fix(input): 修复 Input 组件 切换 type 后不生效的问题
Tencent/tdesign-vue-next pull request #1183
Opened 2022-07-09 06:28 UTC by qdzhaoxiaodao

修复Input 组件 切换 type 后不生效的问题，官网 Input 中组件示例 选择 type 切换时 Input 中的 type 不会变化。

BREAKING CHANGE :
no

closed no

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

1. 修复 Input 组件 切换 type 后不生效的问题，官网 Input 中组件示例 选择 type 切换时 Input 中的 type 不会变化。
2. 添加 watch
3. 复现地址：https://tdesign.tencent.com/vue/components/input 示例中切换 type 即可复现

### 📝 更新日志

无风险
- fix(Input): 修复 Input 组件 切换 type 后不生效的问题

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-07-09 06:35 UTC, timi137137 commented
![image](https://user-images.githubusercontent.com/36812439/178094699-f10415c4-dfc2-4422-a056-3f9afc050551.png)
这是什么

2022-07-09 06:35 UTC, timi137137 commented
![image](https://user-images.githubusercontent.com/36812439/178094707-e0fc1736-c954-4ddf-bfed-ede99b5dc52e.png)
这又是什么

2022-07-09 06:36 UTC, timi137137 commented
![image](https://user-images.githubusercontent.com/36812439/178094716-033d0c63-abfd-494b-9a11-d915f8d618c8.png)
而且你vue的组件你为什么会在vue3的组件库修复

2022-07-09 06:37 UTC, timi137137 requested changes

2022-07-09 06:37 UTC, timi137137 commented on src/input/input.tsx
> +    });
而且不要放在变量声明顶端

2022-07-10 06:46 UTC, pengYYYYY commented on src/input/input.tsx
> +      renderType.value = newProps.type;
renderType的逻辑放在useInput 里面，这一段处理放到那边去吧

2022-07-10 08:38 UTC, qdzhaoxiaodao commented on src/input/input.tsx
> +    });
好的，复现地址因为在vue 也提了一个，复制过来的，我改下

2022-07-10 08:39 UTC, qdzhaoxiaodao commented on src/input/input.tsx
> +      renderType.value = newProps.type;
好的，我修改下

2022-07-10 09:10 UTC, qdzhaoxiaodao commented on src/input/input.tsx
> +    });
已修改

2022-07-10 09:10 UTC, qdzhaoxiaodao commented on src/input/input.tsx
> +      renderType.value = newProps.type;
已修改

2022-07-10 09:15 UTC, timi137137 approved these changes

2022-07-10 15:45 UTC, pengYYYYY commented on src/input/input.tsx
> +import { defineComponent, h, computed, watch } from 'vue';
多余的import

2022-07-12 02:16 UTC, pengYYYYY approved these changes

2022-07-12 02:17 UTC, merged