fix(menu): menuItem超出显示滚动条
Tencent/tdesign-vue-next pull request #1381
Opened 2022-08-10 08:33 UTC by sinbadmaster

closed #1249

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue
#1249 

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-08-11 06:31 UTC, pengYYYYY commented on src/menu/submenu.tsx
> +      // const popupInside = (
这个代码如果不要的话就删掉

2022-08-11 06:31 UTC, pengYYYYY commented on src/menu/submenu.tsx
> +      // return this.isNested ? popupInside : realPopup;
这个代码如果不要的话就删掉

2022-08-15 08:43 UTC, pengYYYYY approved these changes

2022-08-16 08:16 UTC, LeeJim commented
不好意思，我现在认真review下

2022-08-17 13:44 UTC, zhangpaopao0609 commented
> 目前看起来还是会溢出。 是不是和 popup 调整有关。 <img alt="image" width="365" src="https://user-images.githubusercontent.com/7017290/184837423-e6e4922e-9f09-4d72-a425-5ce266ed2f6f.png">

<img width="522" alt="image" src="https://user-images.githubusercontent.com/44194929/185149884-4c1cb428-0066-4a0b-b0e0-d43c4b293e41.png">

2022-08-29 08:38 UTC, LeeJim requested changes

2022-08-29 08:38 UTC, LeeJim commented on src/menu/submenu.tsx
> +      if (target === subPopupRef.value) return;
这里好像永远都是false的。
没理解这个逻辑的作用？

2022-09-03 08:45 UTC, sinbadmaster commented on src/menu/submenu.tsx
> +    const { setSubPopup, closeParentPopup } = submenu ?? {};
好的  好的  填入默认值哈

2022-09-03 08:46 UTC, sinbadmaster commented on src/menu/submenu.tsx
> +        this.isNested && this.isHead ? { marginLeft: '16px' } : { [`margin-${this.isHead ? 'top' : 'left'}`]: '20px' };
是有这个问题  目前还没有处理

2022-09-03 08:58 UTC, sinbadmaster commented on src/menu/submenu.tsx
> +      if (target === subPopupRef.value) return;
<img width="537" alt="image" src="https://user-images.githubusercontent.com/40019023/188263574-17e176ca-f44a-41e5-a3e4-599f265429cb.png">

这里的 subPopupRef 是从submenu中的submenu传递上来的，```if (target === subPopupRef.value) return;```这一行是为了避免多层嵌套具有子popup的时候移动到子下一级的popup的时候关闭了上一级的popup。

2022-09-03 09:41 UTC, sinbadmaster commented on src/menu/submenu.tsx
> +        this.isNested && this.isHead ? { marginLeft: '16px' } : { [`margin-${this.isHead ? 'top' : 'left'}`]: '20px' };
大佬  这里有什么推荐的方法吗？

2022-09-14 07:10 UTC, LeeJim commented on src/menu/submenu.tsx
> +      if (target === subPopupRef.value) return;
get

2022-09-14 07:10 UTC, LeeJim commented on src/menu/submenu.tsx
> +        this.isNested && this.isHead ? { marginLeft: '16px' } : { [`margin-${this.isHead ? 'top' : 'left'}`]: '20px' };
我的建议是不用自定义滚动条

2022-09-19 07:52 UTC, sinbadmaster commented on src/menu/submenu.tsx
> +        this.isNested && this.isHead ? { marginLeft: '16px' } : { [`margin-${this.isHead ? 'top' : 'left'}`]: '20px' };
目前利用自定义滚动条使用的透明背景来解决了这个问题

2022-09-19 10:28 UTC, pengYYYYY approved these changes

2022-09-19 10:28 UTC, pengYYYYY approved these changes

2022-09-19 11:41 UTC, merged