chore: refactor & fix typo
Tencent/tdesign-vue-next pull request #2409
Opened 2023-02-17 04:02 UTC by Simon-He95

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- chore: 重构代码并修正命名的拼写

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-02-17 08:39 UTC, PengYYYYY commented
rebase 一下最新的 develope，这个 PR 有重复内容

2023-02-17 12:31 UTC, Simon-He95 commented
> rebase 一下最新的 develope，这个 PR 有重复内容
我合了最新的 develop, 没有冲突

2023-02-18 02:52 UTC, chaishi commented on src/checkbox/checkbox.tsx
> +      if (!isUndefined(props.disabled)) return props.disabled;
https://github.com/lodash/lodash/blob/master/isUndefined.js

从源代码来源，此处是十分没有必要的改动。反而增加了一个函数上下文

2023-02-18 02:53 UTC, chaishi commented on src/color-picker/panel/index.tsx
> +      if (isNull(recentlyUsedColors.value) || recentlyUsedColors.value === false) {
https://github.com/lodash/lodash/blob/master/isNull.js

从源代码来看，此处的 `isNull` 也是十分没有必要的改动，反而增加了函数执行，请回退。

2023-02-18 02:56 UTC, chaishi commented
PR 改动较多，请仔细确认并检查每一处的 lodash 是否确实值得变更

2023-02-18 16:30 UTC, Simon-He95 commented on src/checkbox/checkbox.tsx
> +      if (!isUndefined(props.disabled)) return props.disabled;
这个wrapper函数确实包了一层函数的执行，但可以忽略不计，他其实就是简化了代码量 === 和 !==,我觉得既然使用了loadash去处理了类似于isNumber等等的函数去重构了，这个isUndefined或者isNull其实也会让代码更加美观一些，后面说的多了import其实可以考虑使用lodash-es 这样lodash的引入都可以结构出来使用在一块

2023-02-18 17:02 UTC, timi137137 commented on src/checkbox/checkbox.tsx
> +      if (!isUndefined(props.disabled)) return props.disabled;
个人同意 chaishi 的看法，使用该函数是没有必要的，单独一行的代码可读性和维护性不会差到哪里去，在非必要情况下尽可能不要使用轮子代替原生比较

2023-02-18 17:14 UTC, timi137137 requested changes
我认为太多地方都不应该修改，请回退一大半无用改动，否则建议closed PR
![image](https://user-images.githubusercontent.com/36812439/219879011-4312f044-b0e1-4d73-886b-6c0b35fc9776.png)
请理解这个仓库是组件仓库，对于很多开发者而言，他们会希望自己的包越小越好，但是根据上图，或者动用知识可以知道。添加无用函数只会使得原有高效的执行效率变得低下，并让打包后的文件变得臃肿，介于以上Request changes

2023-02-18 17:14 UTC, timi137137 commented on src/collapse/collapse-panel.tsx
> +      const tNodeRender = isUndefined(panelExpandIcon.value) ? renderParentTNode : renderTNodeJSX;
跟上面一样，个人认为改不改成lodash函数没有区别，但是如果改成函数容易引发一些意想不到的问题，如无必要请回退

2023-02-18 17:26 UTC, closed without merging