docs: 部分组件增加attach的FAQ
Tencent/tdesign-vue-next pull request #2442
Opened 2023-02-21 07:12 UTC by Aicmortal

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue
- #2422 

### 💡 需求背景和解决方案

### 📝 更新日志

- docs: 部分组件FAQ中增加关于Teleport解释说明

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-02-21 08:59 UTC, uyarn requested changes
逗号需要统一
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/26377630/220297146-9cc304bf-21a1-43e7-913d-18e99b16dbd8.png">

2023-02-21 09:00 UTC, uyarn commented
这句话没必要说 说得越多越让用户不知道混乱 直接给出下面针对这个问题的解决方案就可以了
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/26377630/220297293-5edc98b5-d5d0-4460-83ab-38ce78ec1ecf.png">

2023-02-21 09:38 UTC, Aicmortal commented
> 这句话没必要说 说得越多越让用户越混乱 直接给出下面针对这个问题（样式穿透失效）的解决方案就可以了 <img alt="image" width="1305" src="https://user-images.githubusercontent.com/26377630/220297293-5edc98b5-d5d0-4460-83ab-38ce78ec1ecf.png">

Done,给Guide和ImageViewer也加上了

2023-02-21 12:24 UTC, PengYYYYY commented on src/dialog/dialog.md
> +Dialog 组件在 1.0.8 之后使用 Vue3 的 [Teleport](https://cn.vuejs.org/guide/built-ins/teleport.html) 重构了 `attach` 属性的实现，因此 `:deep()` 深度选择器无法作用于 [Teleport](https://cn.vuejs.org/guide/built-ins/teleport.html) 包
英文和数字都用 `` 括起来吧

2023-02-22 01:17 UTC, uyarn approved these changes

2023-02-22 01:17 UTC, merged