fix(DataPicker): TimePicker cannot be selected time
Tencent/tdesign-vue-next pull request #2842
Opened 2023-05-12 16:21 UTC by coderbaozi

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(DatePicker): 处理问题或特性描述 ...
修复单独使用时TimePicker无法更改问题
- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-05-16 02:37 UTC, PengYYYYY commented
api 平台有修改吗

2023-05-16 02:55 UTC, uyarn approved these changes

2023-05-16 02:57 UTC, uyarn commented
> api 平台有修改吗

@PengYYYYY 这个不是暴露的API 刚好是time-picker的panel需要依赖的 不用录到API平台

2023-05-16 02:58 UTC, uyarn requested changes
只需要保留DatePickerPanel.tsx和DateRangePickerPanel.tsx里增加这个属性就可以了 其他props文件不用增加的

2023-05-16 16:04 UTC, coderbaozi commented
> 只需要保留DatePickerPanel.tsx和DateRangePickerPanel.tsx里增加这个属性就可以了 其他props文件不用增加的
不加prop会有ts类型缺失
~~~js
Property 'popupVisible' does not exist on type 'TdDatePickerPanelProps'.ts(2339)
~~~

2023-05-16 16:12 UTC, coderbaozi commented
> > 只需要保留DatePickerPanel.tsx和DateRangePickerPanel.tsx里增加这个属性就可以了 其他props文件不用增加的
> > 不加prop会有ts类型缺失
> 
> ```js
> Property 'popupVisible' does not exist on type 'TdDatePickerPanelProps'.ts(2339)
> ```



> 只需要保留DatePickerPanel.tsx和DateRangePickerPanel.tsx里增加这个属性就可以了 其他props文件不用增加的

如何不给单独使用的时候popupVisible的default为true，那么单独使用时它的值就是undefined，这样做会不会是不合理的qaq

2023-05-18 06:48 UTC, uyarn commented
> > > 只需要保留DatePickerPanel.tsx和DateRangePickerPanel.tsx里增加这个属性就可以了 其他props文件不用增加的
> > > 不加prop会有ts类型缺失
> > 
> > 
> > ```js
> > Property 'popupVisible' does not exist on type 'TdDatePickerPanelProps'.ts(2339)
> > ```
> 
> > 只需要保留DatePickerPanel.tsx和DateRangePickerPanel.tsx里增加这个属性就可以了 其他props文件不用增加的
> 
> 如何不给单独使用的时候popupVisible的default为true，那么单独使用时它的值就是undefined，这样做会不会是不合理的qaq

我的意思是直接给它传个值 不用props 这个对datepickerpanel 是没去意义的 所以内部用的时候给它默认赋值就行
![image](https://github.com/Tencent/tdesign-vue-next/assets/26377630/77a94acc-5789-4abe-9d7e-c223c75d5662)

2023-05-18 06:49 UTC, uyarn commented
time-picker-panel需要这个值来触发它本身的一些逻辑 是因为在非panel单独使用的场景 面板会有收起的操作 这个时候再触发滚动来变换值的逻辑 会影响面板的正常展示和使用

2023-05-18 16:40 UTC, uyarn approved these changes

2023-05-18 16:40 UTC, uyarn approved these changes

2023-05-18 16:40 UTC, merged