fix: value is '' uncheckable
Tencent/tdesign-vue-next pull request #2950
Opened 2023-06-07 13:34 UTC by kaishuige

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

fix: #2937

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-06-08 02:40 UTC, uyarn requested changes
这里应该是把orgValue.value === ''的条件去掉 因为出现这个缺陷是因为空字符串也加入空值的判断了；然后应该还不止这个地方要修复 clearable的情况下 清空数据也会变成空字符串

2023-06-09 04:15 UTC, kaishuige commented
处理好了 可以再看一下

2023-06-09 05:00 UTC, uyarn commented
spell check看起来新增了规则导致CI fail 了 我先处理下

2023-06-09 08:04 UTC, uyarn approved these changes

2023-06-09 08:06 UTC, merged