fix(drawer): 修复 header 属性无效问题
Tencent/tdesign-vue-next pull request #611
Opened 2022-04-19 09:53 UTC by ZWkang

fix #609

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-04-19 17:18 UTC, pengYYYYY commented
跑一下 npm run test: update

2022-04-19 17:31 UTC, ZWkang commented
@pengYYYYY snapshot update了

2022-04-20 03:30 UTC, LeeJim requested changes

2022-04-20 03:30 UTC, LeeJim commented on src/drawer/drawer.tsx
> +          {headerContent && <div class={`${COMPONENT_NAME}__header`}>{renderTNodeJSX(this, 'header')}</div>}
里面的内容可以直接用 headerContent 了，不用再计算一遍

2022-04-20 03:44 UTC, ZWkang commented on src/drawer/drawer.tsx
> +          {headerContent && <div class={`${COMPONENT_NAME}__header`}>{renderTNodeJSX(this, 'header')}</div>}
fixed

2022-04-20 08:18 UTC, LeeJim approved these changes
LGTM

2022-04-20 08:18 UTC, merged