fix(t-head-menu): t-submenu template #icon not work
Tencent/tdesign-vue-next pull request #643
Opened 2022-04-23 09:16 UTC by fengxianqi

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue
https://github.com/Tencent/tdesign-vue-next/issues/510

### 💡 需求背景和解决方案
解决 [t-header-menu]使用t-submenu template #icon无效的问题

### 📝 更新日志

- fix(t-head-menu): 使用t-submenu template #icon无效的问题

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-04-23 09:41 UTC, pengYYYYY commented on src/menu/submenu.tsx
> +          <span class={[`${this.classPrefix}-menu__content`]}>{renderTNodeJSX(this, 'title', { silent: true })}</span>
为什么要加这一行？

2022-04-23 10:57 UTC, fengxianqi commented on src/menu/submenu.tsx
> +          <span class={[`${this.classPrefix}-menu__content`]}>{renderTNodeJSX(this, 'title', { silent: true })}</span>
这是测试时额外发现的问题，当` <t-head-menu expand-type="normal">`时，icon也不能正常渲染，因此这里是兼容了`expand-type="normal"`的这种情况

2022-04-23 11:55 UTC, pengYYYYY commented on src/menu/submenu.tsx
> +          <span class={[`${this.classPrefix}-menu__content`]}>{renderTNodeJSX(this, 'title', { silent: true })}</span>
了解

2022-04-25 15:09 UTC, pengYYYYY commented
https://github.com/Tencent/tdesign-vue-next/issues/326 这边有一些任务，有兴趣可以参与

2022-04-26 11:20 UTC, LeeJim requested changes

2022-04-26 11:20 UTC, LeeJim commented on src/menu/submenu.tsx
> +      const needRotate = this.mode === 'popup';
这里的 this.isNested 为啥要移除？

2022-04-26 11:20 UTC, LeeJim commented on src/menu/submenu.tsx
> +          style="display:block"
加这个的用意是？

2022-04-26 11:28 UTC, fengxianqi commented on src/menu/submenu.tsx
> +      const needRotate = this.mode === 'popup';
这是为了修复当expandType=popup时箭头方向错误的问题，对应这个issue：https://github.com/Tencent/tdesign-vue/pull/806
<img width="940" alt="image" src="https://user-images.githubusercontent.com/15716381/165290207-b8b97d17-e754-490c-9f58-432bcdcf2590.png">

2022-04-26 11:31 UTC, fengxianqi commented on src/menu/submenu.tsx
> +          style="display:block"
当expandType="popup"时，.t-popup__reference的样式会导致无法撑开宽度（预期是撑开到绿色框），这里是为了覆盖这个样式
<img width="2252" alt="企业微信截图_6bf31f05-6aa5-4ca1-ba95-2223bac4ec9d" src="https://user-images.githubusercontent.com/15716381/165290457-877301a3-312a-4f1d-af0d-5ee589616447.png">

2022-04-29 02:47 UTC, LeeJim commented on src/menu/submenu.tsx
> +          style="display:block"
OK的

2022-04-29 02:51 UTC, LeeJim commented on src/menu/submenu.tsx
> +      const needRotate = this.mode === 'popup';
设计师反馈，这个设计是不OK的，等我和设计师沟通后再反馈一下吧

2022-05-05 04:00 UTC, pengYYYYY commented
能否先处理fix(t-head-menu): 使用t-submenu template #icon无效的问题

2022-05-05 06:55 UTC, fengxianqi commented
已update为只修复一个问题 @pengYYYYY

2022-05-05 14:42 UTC, pengYYYYY commented
处理一下冲突，这个PR应该不需要更新common的

2022-05-06 06:06 UTC, merged